language: java
sudo: false

jdk:
  - oraclejdk8

install:
  - cd server/sonar-web
  - npm install

before_script:
  - npm run build-test
  - cd ../..

script:
  - mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
